// Default icons
export { default as arrowLeft } from './svg/icons/default/arrow-left.svg';
export { default as arrowRight } from './svg/icons/default/arrow-right.svg';
export { default as chevronRight } from './svg/icons/default/chevron-right.svg';
export { default as chevronLeft } from './svg/icons/default/chevron-left.svg';
export { default as circle } from './svg/icons/default/circle.svg';
export { default as heatMap } from './svg/icons/default/heatmap.svg';
export { default as rates } from './svg/icons/default/rates.svg';
export { default as main } from './svg/icons/default/home.svg';
export { default as speakerPhone } from './svg/icons/default/speakerphone.svg';
export { default as tag } from './svg/icons/default/tag.svg';
export { default as template } from './svg/icons/default/template.svg';
export { default as identification } from './svg/icons/default/identification.svg';
export { default as logo } from './svg/icons/default/logo.svg';
export { default as logoPrimary } from './svg/icons/default/we_way_logo_primary.svg';
export { default as promoCode } from './svg/icons/default/promocode.svg';
export { default as users } from './svg/icons/default/users.svg';
export { default as laptop } from './svg/icons/default/Laptop.svg';
export { default as officeBuilding } from './svg/icons/default/office-building.svg';
export { default as referrals } from './svg/icons/default/rreferrals.svg';
export { default as settings } from './svg/icons/default/settings.svg';
export { default as logout } from './svg/icons/default/logout.svg';
export { default as add } from './svg/icons/default/add.svg';
export { default as edit } from './svg/icons/default/edit.svg';
export { default as plus } from './svg/icons/default/blue-plus.svg';
export { default as active } from './svg/icons/default/check-circle.svg';
export { default as status } from './svg/icons/default/Component 1.svg';
export { default as x } from './svg/icons/default/x-circle.svg';
export { default as search } from './svg/icons/default/search.svg';
export { default as infoCircle } from './svg/icons/default/information-circle.svg';
export { default as eng } from './svg/icons/default/ENG.svg';
export { default as rus } from './svg/icons/default/RU.svg';
export { default as kg } from './svg/icons/default/KG.svg';
export { default as warning } from './svg/icons/default/warning.svg';
export { default as greenCheck } from './svg/icons/default/greenCheck.svg';
export { default as inactive } from './svg/icons/default/inactive.svg';
export { default as trendingUp } from './svg/icons/default/trending-up.svg';
export { default as trendingDown } from './svg/icons/default/trending-down.svg';
export { default as userGroup } from './svg/icons/default/user-group.svg';
export { default as editColor } from './svg/icons/default/edit-color.svg';
export { default as deleteIcon } from './svg/icons/default/Delete.svg';

// Active icons
export { default as circleActive } from './svg/icons/active/circle-active.svg';
export { default as heatMapActive } from './svg/icons/active/heatmap-active.svg';
export { default as ratesActive } from './svg/icons/active/rates-active.svg';
export { default as mainActive } from './svg/icons/active/home-active.svg';
export { default as speakerPhoneActive } from './svg/icons/active/speakerphone-active.svg';
export { default as tagActive } from './svg/icons/active/tag-active.svg';
export { default as templateActive } from './svg/icons/active/template-active.svg';
export { default as identificationActive } from './svg/icons/active/identification-active.svg';
export { default as promoCodeActive } from './svg/icons/active/promocode-active.svg';
export { default as laptopActive } from './svg/icons/active/laptop-active.svg';
export { default as officeBuildingActive } from './svg/icons/active/office-building-active.svg';
export { default as referralsActive } from './svg/icons/active/rreferrals-active.svg';
export { default as settingsActive } from './svg/icons/active/settings-active.svg';
export { default as logoutActive } from './svg/icons/active/logout-active.svg';
export { default as usersActive } from './svg/icons/active/user-group-active.svg';
export { default as point } from './svg/icons/active/point.svg';

// images
export { default as notFoundImage } from './png/images/Add tasks-pana 1.png';
export { default as emptyImage } from './png/images/empty-image.png';
