version: '3'

services:
  ev-dashboard:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.test
    environment:
      - REACT_APP_ENVIRONMENT=testing
      - REACT_APP_API_URL=0.0.0.0:8000
    command: yarn test -u
    networks:
      - testing

networks:
  testing:

