FROM node:18-slim as builder

ARG VITE_API_SENTRY_DSN

ENV VITE_API_SENTRY_DSN=${VITE_API_SENTRY_DSN}

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

RUN yarn build
CMD [ "yarn start" ]
